import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export type SupportedLanguage = 'en' | 'tr';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  flag: string;
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLangSubject = new BehaviorSubject<SupportedLanguage>(this.getInitialLanguage());
  public currentLang$: Observable<SupportedLanguage> = this.currentLangSubject.asObservable();

  public readonly languages: LanguageOption[] = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'tr', name: 'Türkçe', flag: '🇹🇷' }
  ];

  private translations: Record<SupportedLanguage, Record<string, string>> = {
    en: {
      // Navigation & Sidebar
      'Dashboard': 'Dashboard',
      'Operational Dashboard': 'Operational Dashboard',
      'Core': 'Core',
      'Reservations': 'Reservations',
      'Customers': 'Customers',
      'Agencies': 'Agencies',
      'Payments': 'Payments',
      'Exchange Rates': 'Exchange Rates',
      'Setup': 'Setup',
      'Configuration': 'Configuration',
      'Pilots': 'Pilots',
      'Flight Packages': 'Flight Packages',
      'Extra Services': 'Extra Services',
      'Transport Groups': 'Transport Groups',
      'Flight Times': 'Flight Times',
      'System User Manual': 'System User Manual',
      'User Manual': 'User Manual',
      'Admin': 'Admin',
      'Help': 'Help',
      'My Profile': 'My Profile',
      'Manage Users': 'Manage Users',
      'Sign Out': 'Sign Out',
      'Update Rate': 'Update Rate',
      'Amount': 'Amount',

      // Dashboard
      'Total Reservations': 'Total Reservations',
      'Today\'s Flights': 'Today\'s Flights',
      'Total Revenue': 'Total Revenue',
      'Active Customers': 'Active Customers',
      'Today\'s Flight Schedule': 'Today\'s Flight Schedule',
      'Quick Actions': 'Quick Actions',
      'New Reservation': 'New Reservation',
      'Process Payment': 'Process Payment',
      'Check Exchange Rates': 'Check Exchange Rates',
      'System Overview': 'System Overview',
      'View All': 'View All',
      'Passengers': 'Passengers',
      'Passenger': 'Passenger',
      'Reservation': 'Reservation',
      'Currency API Online': 'Currency API Online',
      'System Secure': 'System Secure',
      'No flights scheduled for today.': 'No flights scheduled for today.',
      'Get started by adding a new reservation!': 'Get started by adding a new reservation!',

      // Common Actions, Headers & Breadcrumbs
      'Home': 'Home',
      'Entities': 'Entities',
      'Logistics & Packages': 'Logistics & Packages',
      'Settings': 'Settings',
      'Add': 'Add',
      'Create': 'Create',
      'Edit': 'Edit',
      'Delete': 'Delete',
      'Save': 'Save',
      'Save Changes': 'Save Changes',
      'Cancel': 'Cancel',
      'Close': 'Close',
      'Search': 'Search',
      'Filter': 'Filter',
      'Filters': 'Filters',
      'Clear': 'Clear',
      'Reset': 'Reset',
      'Actions': 'Actions',
      'Action': 'Action',
      'Status': 'Status',
      'Active': 'Active',
      'Inactive': 'Inactive',
      'Pending': 'Pending',
      'Confirmed': 'Confirmed',
      'Cancelled': 'Cancelled',
      'Total': 'Total',
      'Price': 'Price',
      'Date': 'Date',
      'Time': 'Time',
      'Slot': 'Slot',
      'Notes': 'Notes',
      'Note': 'Note',
      'Export Excel': 'Export Excel',
      'Print': 'Print',
      'Welcome Back': 'Welcome Back',
      'Sign In': 'Sign In',
      'Username': 'Username',
      'Password': 'Password',
      'Users': 'Users',
      'General Information': 'General Information',
      'View': 'View',
      'Previous Day': 'Previous Day',
      'Next Day': 'Next Day',
      'ID': 'ID',
      'Remove': 'Remove',

      // Customers
      'Customers Management': 'Customers Management',
      'Total Customers': 'Total Customers',
      'Nationalities': 'Nationalities',
      'With Contact Info': 'With Contact Info',
      'Customer': 'Customer',
      'Full Name': 'Full Name',
      'Date of Birth': 'Date of Birth',
      'Date of Birth & Age': 'Date of Birth & Age',
      'Phone Number': 'Phone Number',
      'Email Address': 'Email Address',
      'Email': 'Email',
      'Country': 'Country',
      'Country / Nationality': 'Country / Nationality',
      'Add Customer': 'Add Customer',
      'Add New Customer': 'Add New Customer',
      'Edit Customer': 'Edit Customer',
      'No customers found': 'No customers found',
      'Add Your First Customer': 'Add Your First Customer',

      // Pilots
      'Pilots Management': 'Pilots Management',
      'Total Pilots': 'Total Pilots',
      'Pilot Groups': 'Pilot Groups',
      'Total Flights Flown': 'Total Flights Flown',
      'Pilots Directory': 'Pilots Directory',
      'Flight Roster': 'Flight Roster',
      'Manage Groups': 'Manage Groups',
      'Add Pilot': 'Add Pilot',
      'Edit Pilot': 'Edit Pilot',
      'Save Pilot': 'Save Pilot',
      'License Number': 'License Number',
      'Pilot Group': 'Pilot Group',
      'Flights Assigned': 'Flights Assigned',
      'Flights Flown': 'Flights Flown',
      'Did Not Come': 'Did Not Come',
      'No-Show': 'No-Show',
      'Group': 'Group',
      'No Group': 'No Group',
      'No Group / Independent': 'No Group / Independent',
      'No pilots found. Click "Add Pilot" to create one.': 'No pilots found. Click "Add Pilot" to create one.',
      'No pilot flight assignments found. Add pilots to reservations to see them here!': 'No pilot flight assignments found. Add pilots to reservations to see them here!',
      'Flight Metrics Override': 'Flight Metrics Override',
      'These numbers automatically increment via the Flight Roster. You can manually adjust them here if needed.': 'These numbers automatically increment via the Flight Roster. You can manually adjust them here if needed.',
      'Pilot Groups Management': 'Pilot Groups Management',
      'Edit Group': 'Edit Group',
      'Create New Group': 'Create New Group',
      'Create Group': 'Create Group',
      'Update Group': 'Update Group',
      'Enter group name...': 'Enter group name...',
      'Existing Groups': 'Existing Groups',
      'Group Name': 'Group Name',
      'Active Pilots': 'Active Pilots',
      'No pilot groups created yet.': 'No pilot groups created yet.',

      // Agencies
      'Agencies Management': 'Agencies Management',
      'Manage your partner agencies and their contact information.': 'Manage your partner agencies and their contact information.',
      'Add New Agency': 'Add New Agency',
      'Edit Agency': 'Edit Agency',
      'New Agency': 'New Agency',
      'Update Agency': 'Update Agency',
      'Save Agency': 'Save Agency',
      'Agency Name': 'Agency Name',
      'Contact Person': 'Contact Person',
      'Office Address': 'Office Address',
      'No contact person': 'No contact person',
      'No address provided': 'No address provided',
      'No agencies found': 'No agencies found',
      'You haven\'t added any partner agencies yet.': 'You haven\'t added any partner agencies yet.',
      'Add Your First Agency': 'Add Your First Agency',

      // Extra Services
      'Extra Services Management': 'Extra Services Management',
      'Total Services': 'Total Services',
      'Average Price': 'Average Price',
      'Photo & Video Add-ons': 'Photo & Video Add-ons',
      'Add Extra Service': 'Add Extra Service',
      'Add New Extra Service': 'Add New Extra Service',
      'Edit Extra Service': 'Edit Extra Service',
      'Service Name': 'Service Name',
      'Retail Price': 'Retail Price',
      'No extra services found': 'No extra services found',
      'Schedule First Extra Service': 'Schedule First Extra Service',

      // Transport Groups
      'Transport Groups Management': 'Transport Groups Management',
      'Total Shuttles': 'Total Shuttles',
      'Active Fleet Vehicles': 'Active Fleet Vehicles',
      'Designated Drivers': 'Designated Drivers',
      'Add Transport Group': 'Add Transport Group',
      'New Transport Group': 'New Transport Group',
      'Edit Transport Group': 'Edit Transport Group',
      'Departure Date & Time': 'Departure Date & Time',
      'Departure Time': 'Departure Time',
      'Vehicle Plate Number': 'Vehicle Plate Number',
      'Vehicle Plate': 'Vehicle Plate',
      'Driver Full Name': 'Driver Full Name',
      'Driver Name': 'Driver Name',
      'Assigned Driver': 'Assigned Driver',
      'Mountain Transfer': 'Mountain Transfer',
      'Shuttle Departure': 'Shuttle Departure',
      'No transport groups found': 'No transport groups found',
      'Schedule First Mountain Shuttle': 'Schedule First Mountain Shuttle',

      // Flight Packages
      'Manage your available flight packages and pricing tiers.': 'Manage your available flight packages and pricing tiers.',
      'Add New Package': 'Add New Package',
      'Edit Flight Package': 'Edit Flight Package',
      'Create New Package': 'Create New Package',
      'Create Package': 'Create Package',
      'Package Title': 'Package Title',
      'Package Description': 'Package Description',
      'Describe what\'s included in this package...': 'Describe what\'s included in this package...',
      'No packages found': 'No packages found',
      'You haven\'t created any flight packages yet. Start by adding one!': 'You haven\'t created any flight packages yet. Start by adding one!',
      'Create Your First Package': 'Create Your First Package',
      'person': 'person',
      'Photos and videos': 'Photos and videos',
      '20-30 min': '20-30 min',
      'Explore the skies with this premium paragliding experience. Perfect for thrill-seekers and nature lovers alike.': 'Explore the skies with this premium paragliding experience. Perfect for thrill-seekers and nature lovers alike.',

      // Flight Times
      'Flight Time Management': 'Flight Time Management',
      'Available Time Slots': 'Available Time Slots',
      'Time Slot': 'Time Slot',
      'Time Slots': 'Time Slots',
      'Flight Time Slots': 'Flight Time Slots',
      'Add Time Slot': 'Add Time Slot',
      'Add New Slot': 'Add New Slot',
      'Edit Time Slot': 'Edit Time Slot',
      'Update Slot': 'Update Slot',
      'Save Slot': 'Save Slot',
      'Cancel Edit': 'Cancel Edit',
      'Time (e.g. 08:30)': 'Time (e.g. 08:30)',
      'Active Status': 'Active Status',
      'Dynamic Scheduling': 'Dynamic Scheduling',
      'Changes made here will immediately appear in the reservation form and filtering options.': 'Changes made here will immediately appear in the reservation form and filtering options.',
      'No flight times defined.': 'No flight times defined.',

      // Exchange Rates
      'Refresh Rates': 'Refresh Rates',
      'Refreshing...': 'Refreshing...',
      'Currency Converter': 'Currency Converter',
      'Amount to Convert': 'Amount to Convert',
      'From': 'From',
      'To': 'To',
      'Converted Amount': 'Converted Amount',
      'Detailed Conversion Table (Base: 1 USD)': 'Detailed Conversion Table (Base: 1 USD)',
      'Currency Code': 'Currency Code',
      'Currency Name': 'Currency Name',
      'Rate to 1 USD': 'Rate to 1 USD',
      'Rate to 1 TRY': 'Rate to 1 TRY',
      'Last updated:': 'Last updated:',

      // Payments
      'Payments Management': 'Payments Management',
      'Payment Hub': 'Payment Hub',
      'Collect Payments': 'Collect Payments',
      'Payment Records': 'Payment Records',
      'Daily Revenue Ledger': 'Daily Revenue Ledger',
      'Select Date:': 'Select Date:',
      'Transactions': 'Transactions',
      'TRY Collected': 'TRY Collected',
      'USD Collected': 'USD Collected',
      'EUR Collected': 'EUR Collected',
      'GBP Collected': 'GBP Collected',
      'Payment Method': 'Payment Method',
      'All Methods': 'All Methods',
      'All Currencies': 'All Currencies',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Search by Reservation ID, Title, or Passenger Name...': 'Search by Reservation ID, Title, or Passenger Name...',
      'Amount Paid': 'Amount Paid',
      'Method': 'Method',
      'No transaction records found matching your filters.': 'No transaction records found matching your filters.',
      'No flights scheduled for this slot.': 'No flights scheduled for this slot.',
      'Paid in Full': 'Paid in Full',
      'Paid': 'Paid',
      'Non Paid': 'Non Paid',
      'Pending Balance': 'Pending Balance',
      'Rest to Pay': 'Rest to Pay',
      'Cash': 'Cash',
      'Credit Card': 'Credit Card',
      'Card': 'Card',
      'Bank Transfer': 'Bank Transfer',
      'Transfer': 'Transfer',
      'Transfer/IBAN': 'Transfer/IBAN',
      'Refund': 'Refund',
      'Receipt': 'Receipt',
      'Make Payment': 'Make Payment',
      'Issue Refund': 'Issue Refund',
      'Deposit': 'Deposit',
      'Pay': 'Pay',
      'Print Thermal Bill (80mm)': 'Print Thermal Bill (80mm)',
      'Payment': 'Payment',
      'Confirm Payment': 'Confirm Payment',
      'Confirm Refund': 'Confirm Refund',
      'Pay All': 'Pay All',
      'Refund All': 'Refund All',
      'Refund Amount': 'Refund Amount',
      'Pay in Currency': 'Pay in Currency',
      'Rest': 'Rest',
      'Equivalent in': 'Equivalent in',
      'Exchange Rate': 'Exchange Rate',

      // Reservations & Reservation Form
      'Reservations Dashboard': 'Reservations Dashboard',
      'Schedule View': 'Schedule View',
      'Schedule Matrix': 'Schedule Matrix',
      'List View': 'List View',
      'Print PDF': 'Print PDF',
      'Print PDF Manifest': 'Print PDF Manifest',
      'Print Voucher': 'Print Voucher',
      'Slots': 'Slots',
      'No reservations for this slot.': 'No reservations for this slot.',
      'PAX': 'PAX',
      'Reservation Title': 'Reservation Title',
      'Booking Source': 'Booking Source',
      'Flight Date': 'Flight Date',
      'Booking Status': 'Booking Status',
      'Booking Channel': 'Booking Channel',
      'Direct Booking (Us)': 'Direct Booking (Us)',
      'Direct Booking': 'Direct Booking',
      'Agency Booking': 'Agency Booking',
      'Agency': 'Agency',
      'Select Agency': 'Select Agency',
      'Pickup Hotel': 'Pickup Hotel',
      'Room Number': 'Room Number',
      'Passenger Weight': 'Passenger Weight',
      'Weight': 'Weight',
      'Assigned Pilot': 'Assigned Pilot',
      'Takeoff Time': 'Takeoff Time',
      'Passengers Details': 'Passengers Details',
      'Add Passenger': 'Add Passenger',
      'Total Due': 'Total Due',
      'Deposit Paid': 'Deposit Paid',
      'Payment Currency': 'Payment Currency',
      'Preferred Currency': 'Preferred Currency',
      'Total Amount': 'Total Amount',
      'Billet Number': 'Billet Number',
      'Billet / Ticket Number': 'Billet / Ticket Number',
      'Passenger Information': 'Passenger Information',
      'Passenger Details': 'Passenger Details',
      'Search Existing Customer': 'Search Existing Customer',
      'Start typing name...': 'Start typing name...',
      'Nationality': 'Nationality',
      'Select Country': 'Select Country',
      'Filter by Group': 'Filter by Group',
      'Select Pilot': 'Select Pilot',
      'Flight Package': 'Flight Package',
      'Choose Package': 'Choose Package',
      'Transport': 'Transport',
      'Select Service': 'Select Service',
      'Select Extras': 'Select Extras',
      'Passenger Weight Limit Verified': 'Passenger Weight Limit Verified',
      'Add Another Passenger to this Reservation': 'Add Another Passenger to this Reservation',
      'Pickup & Logistics': 'Pickup & Logistics',
      'Pickup Service': 'Pickup Service',
      'Pickup Location / Hotel Name': 'Pickup Location / Hotel Name',
      'Enter hotel or location name': 'Enter hotel or location name',
      'Additional Information': 'Additional Information',
      'Special Requests or Notes': 'Special Requests or Notes',
      'Any dietary requirements, health issues, or special occasions?': 'Any dietary requirements, health issues, or special occasions?',
      'Reservation Photos / Documents': 'Reservation Photos / Documents',
      'Upload Photos (e.g. payment receipt, passport copy, ticket files)': 'Upload Photos (e.g. payment receipt, passport copy, ticket files)',
      'Drag & drop files here, or click to browse': 'Drag & drop files here, or click to browse',
      'Choose Photos': 'Choose Photos',
      'Complete Booking': 'Complete Booking',
      'Update Reservation': 'Update Reservation',
      'Please provide the flight and passenger details below.': 'Please provide the flight and passenger details below.',
      'Book a New Flight': 'Book a New Flight',
      'Update Flight Details': 'Update Flight Details',
      'Loading reservations...': 'Loading reservations...',
      'Saving reservation...': 'Saving reservation...',
      'Financial Summary': 'Financial Summary',
      'Total Price': 'Total Price',
      'Total Paid': 'Total Paid',
      'Remaining Due': 'Remaining Due',
      'Booking Channels': 'Booking Channels',
      'Booking Overview': 'Booking Overview',
      'Total PAX (Passengers)': 'Total PAX (Passengers)',
      'No channel data available': 'No channel data available',
      'No reservations found matching your criteria.': 'No reservations found matching your criteria.',
      'Date Range': 'Date Range',
      'Selected Day': 'Selected Day',
      'One Week': 'One Week',
      'One Month': 'One Month',
      'One Year': 'One Year',
      'All Time': 'All Time',
      'All Statuses': 'All Statuses',
      'All Times': 'All Times',
      'Title / Type': 'Title / Type',
      'Amount / Paid': 'Amount / Paid',

      // User Management & Profile
      'User Management': 'User Management',
      'System Users': 'System Users',
      'Add New User': 'Add New User',
      'User': 'User',
      'Roles': 'Roles',
      'Reset Password': 'Reset Password',
      'User Profile': 'User Profile',
      'Profile': 'Profile',
      'Profile Details': 'Profile Details',
      'Account Type': 'Account Type',
      'Member Since': 'Member Since',
      'Overview': 'Overview'
    },
    tr: {
      // Navigation & Sidebar
      'Dashboard': 'Kontrol Paneli',
      'Operational Dashboard': 'Operasyonel Kontrol Paneli',
      'Core': 'Temel İşlemler',
      'Reservations': 'Rezervasyonlar',
      'Customers': 'Müşteriler',
      'Agencies': 'Acenteler',
      'Payments': 'Ödemeler',
      'Exchange Rates': 'Döviz Kurları',
      'Setup': 'Kurulum',
      'Configuration': 'Yapılandırma',
      'Pilots': 'Pilotlar',
      'Flight Packages': 'Uçuş Paketleri',
      'Extra Services': 'Ek Hizmetler',
      'Transport Groups': 'Transfer Grupları',
      'Flight Times': 'Uçuş Saatleri',
      'System User Manual': 'Kullanım Kılavuzu',
      'User Manual': 'Kullanım Kılavuzu',
      'Admin': 'Yönetici',
      'Help': 'Yardım',
      'My Profile': 'Profilim',
      'Manage Users': 'Kullanıcıları Yönet',
      'Sign Out': 'Çıkış Yap',
      'Update Rate': 'Kurları Güncelle',
      'Amount': 'Tutar',

      // Dashboard
      'Total Reservations': 'Toplam Rezervasyon',
      'Today\'s Flights': 'Günün Uçuşları',
      'Total Revenue': 'Toplam Gelir',
      'Active Customers': 'Aktif Müşteriler',
      'Today\'s Flight Schedule': 'Günün Uçuş Programı',
      'Quick Actions': 'Hızlı İşlemler',
      'New Reservation': 'Yeni Rezervasyon',
      'Process Payment': 'Ödeme Al / İşle',
      'Check Exchange Rates': 'Döviz Kurlarını İncele',
      'System Overview': 'Sistem Özeti',
      'View All': 'Tümünü Gör',
      'Passengers': 'Yolcular',
      'Passenger': 'Yolcu',
      'Reservation': 'Rezervasyon',
      'Currency API Online': 'Döviz API Çevrimiçi',
      'System Secure': 'Sistem Güvenli',
      'No flights scheduled for today.': 'Bugün için planlanmış uçuş bulunmuyor.',
      'Get started by adding a new reservation!': 'Yeni bir rezervasyon ekleyerek başlayın!',

      // Common Actions, Headers & Breadcrumbs
      'Home': 'Ana Sayfa',
      'Entities': 'Kayıtlar',
      'Logistics & Packages': 'Lojistik ve Paketler',
      'Settings': 'Ayarlar',
      'Add': 'Ekle',
      'Create': 'Oluştur',
      'Edit': 'Düzenle',
      'Delete': 'Sil',
      'Save': 'Kaydet',
      'Save Changes': 'Değişiklikleri Kaydet',
      'Cancel': 'İptal',
      'Close': 'Kapat',
      'Search': 'Ara',
      'Filter': 'Filtrele',
      'Filters': 'Filtreler',
      'Clear': 'Temizle',
      'Reset': 'Sıfırla',
      'Actions': 'İşlemler',
      'Action': 'İşlem',
      'Status': 'Durum',
      'Active': 'Aktif',
      'Inactive': 'Pasif',
      'Pending': 'Beklemede',
      'Confirmed': 'Onaylandı',
      'Cancelled': 'İptal Edildi',
      'Total': 'Toplam',
      'Price': 'Fiyat',
      'Date': 'Tarih',
      'Time': 'Saat',
      'Slot': 'Saat Dilimi',
      'Notes': 'Notlar',
      'Note': 'Not',
      'Export Excel': 'Excel\'e Aktar',
      'Print': 'Yazdır',
      'Welcome Back': 'Tekrar Hoş Geldiniz',
      'Sign In': 'Giriş Yap',
      'Username': 'Kullanıcı Adı',
      'Password': 'Şifre',
      'Users': 'Kullanıcılar',
      'General Information': 'Genel Bilgiler',
      'View': 'Görüntüle',
      'Previous Day': 'Önceki Gün',
      'Next Day': 'Sonraki Gün',
      'ID': 'No',
      'Remove': 'Kaldır',

      // Customers
      'Customers Management': 'Müşteri Yönetimi',
      'Total Customers': 'Toplam Müşteri',
      'Nationalities': 'Uyruk Sayısı',
      'With Contact Info': 'İletişim Bilgili',
      'Customer': 'Müşteri',
      'Full Name': 'Ad Soyad',
      'Date of Birth': 'Doğum Tarihi',
      'Date of Birth & Age': 'Doğum Tarihi ve Yaş',
      'Phone Number': 'Telefon Numarası',
      'Email Address': 'E-posta Adresi',
      'Email': 'E-posta',
      'Country': 'Ülke',
      'Country / Nationality': 'Ülke / Uyruk',
      'Add Customer': 'Müşteri Ekle',
      'Add New Customer': 'Yeni Müşteri Ekle',
      'Edit Customer': 'Müşteriyi Düzenle',
      'No customers found': 'Müşteri bulunamadı',
      'Add Your First Customer': 'İlk Müşteriyi Ekle',

      // Pilots
      'Pilots Management': 'Pilot Yönetimi',
      'Total Pilots': 'Toplam Pilot',
      'Pilot Groups': 'Pilot Grupları',
      'Total Flights Flown': 'Toplam Yapılan Uçuş',
      'Pilots Directory': 'Pilot Rehberi',
      'Flight Roster': 'Uçuş Nöbet Listesi',
      'Manage Groups': 'Grupları Yönet',
      'Add Pilot': 'Pilot Ekle',
      'Edit Pilot': 'Pilotu Düzenle',
      'Save Pilot': 'Pilotu Kaydet',
      'License Number': 'Lisans Numarası',
      'Pilot Group': 'Pilot Grubu',
      'Flights Assigned': 'Atanan Uçuşlar',
      'Flights Flown': 'Tamamlanan Uçuşlar',
      'Did Not Come': 'Gelmeyen (No-Show)',
      'No-Show': 'Gelmeyen',
      'Group': 'Grup',
      'No Group': 'Grup Yok',
      'No Group / Independent': 'Grup Yok / Bağımsız',
      'No pilots found. Click "Add Pilot" to create one.': 'Pilot bulunamadı. Oluşturmak için "Pilot Ekle"ye tıklayın.',
      'No pilot flight assignments found. Add pilots to reservations to see them here!': 'Pilot uçuş görevi bulunamadı. Görmek için rezervasyonlara pilot atayın!',
      'Flight Metrics Override': 'Uçuş İstatistiklerini Düzenle',
      'These numbers automatically increment via the Flight Roster. You can manually adjust them here if needed.': 'Bu sayılar Uçuş Nöbet Listesi üzerinden otomatik artar. Gerekirse buradan manuel güncelleyebilirsiniz.',
      'Pilot Groups Management': 'Pilot Grupları Yönetimi',
      'Edit Group': 'Grubu Düzenle',
      'Create New Group': 'Yeni Grup Oluştur',
      'Create Group': 'Grup Oluştur',
      'Update Group': 'Grubu Güncelle',
      'Enter group name...': 'Grup adını girin...',
      'Existing Groups': 'Mevcut Gruplar',
      'Group Name': 'Grup Adı',
      'Active Pilots': 'Aktif Pilotlar',
      'No pilot groups created yet.': 'Henüz oluşturulmuş pilot grubu yok.',

      // Agencies
      'Agencies Management': 'Acente Yönetimi',
      'Manage your partner agencies and their contact information.': 'Ortak acentelerinizi ve iletişim bilgilerini yönetin.',
      'Add New Agency': 'Yeni Acente Ekle',
      'Edit Agency': 'Acenteyi Düzenle',
      'New Agency': 'Yeni Acente',
      'Update Agency': 'Acenteyi Güncelle',
      'Save Agency': 'Acenteyi Kaydet',
      'Agency Name': 'Acente Adı',
      'Contact Person': 'Yetkili Kişi',
      'Office Address': 'Ofis Adresi',
      'No contact person': 'Yetkili kişi yok',
      'No address provided': 'Adres belirtilmemiş',
      'No agencies found': 'Acente bulunamadı',
      'You haven\'t added any partner agencies yet.': 'Henüz ortak acente eklemediniz.',
      'Add Your First Agency': 'İlk Acenteyi Ekle',

      // Extra Services
      'Extra Services Management': 'Ek Hizmet Yönetimi',
      'Total Services': 'Toplam Hizmet',
      'Average Price': 'Ortalama Fiyat',
      'Photo & Video Add-ons': 'Fotoğraf ve Video Paketleri',
      'Add Extra Service': 'Ek Hizmet Ekle',
      'Add New Extra Service': 'Yeni Ek Hizmet Ekle',
      'Edit Extra Service': 'Ek Hizmeti Düzenle',
      'Service Name': 'Hizmet Adı',
      'Retail Price': 'Satış Fiyatı',
      'No extra services found': 'Ek hizmet bulunamadı',
      'Schedule First Extra Service': 'İlk Ek Hizmeti Ekle',

      // Transport Groups
      'Transport Groups Management': 'Transfer Grupları Yönetimi',
      'Total Shuttles': 'Toplam Servis',
      'Active Fleet Vehicles': 'Aktif Araç Filosu',
      'Designated Drivers': 'Görevli Sürücüler',
      'Add Transport Group': 'Transfer Grubu Ekle',
      'New Transport Group': 'Yeni Transfer Grubu',
      'Edit Transport Group': 'Transfer Grubunu Düzenle',
      'Departure Date & Time': 'Kalkış Tarihi ve Saati',
      'Departure Time': 'Kalkış Saati',
      'Vehicle Plate Number': 'Araç Plaka Numarası',
      'Vehicle Plate': 'Araç Plakası',
      'Driver Full Name': 'Sürücü Adı Soyadı',
      'Driver Name': 'Sürücü Adı',
      'Assigned Driver': 'Atanan Sürücü',
      'Mountain Transfer': 'Dağ Transferi',
      'Shuttle Departure': 'Servis Kalkışı',
      'No transport groups found': 'Transfer grubu bulunamadı',
      'Schedule First Mountain Shuttle': 'İlk Dağ Servisini Planla',

      // Flight Packages
      'Manage your available flight packages and pricing tiers.': 'Mevcut uçuş paketlerinizi ve fiyat tarifelerinizi yönetin.',
      'Add New Package': 'Yeni Paket Ekle',
      'Edit Flight Package': 'Uçuş Paketini Düzenle',
      'Create New Package': 'Yeni Paket Oluştur',
      'Create Package': 'Paket Oluştur',
      'Package Title': 'Paket Başlığı',
      'Package Description': 'Paket Açıklaması',
      'Describe what\'s included in this package...': 'Bu pakete nelerin dahil olduğunu açıklayın...',
      'No packages found': 'Paket bulunamadı',
      'You haven\'t created any flight packages yet. Start by adding one!': 'Henüz uçuş paketi oluşturmadınız. Bir tane ekleyerek başlayın!',
      'Create Your First Package': 'İlk Paketi Oluştur',
      'person': 'kişi',
      'Photos and videos': 'Fotoğraf ve video',
      '20-30 min': '20-30 dk',
      'Explore the skies with this premium paragliding experience. Perfect for thrill-seekers and nature lovers alike.': 'Bu premium yamaç paraşütü deneyimiyle gökyüzünü keşfedin. Heyecan arayanlar ve doğa severler için mükemmel.',

      // Flight Times
      'Flight Time Management': 'Uçuş Saatleri Yönetimi',
      'Available Time Slots': 'Mevcut Saat Dilimleri',
      'Time Slot': 'Saat Dilimi',
      'Time Slots': 'Saat Dilimleri',
      'Flight Time Slots': 'Uçuş Saatleri',
      'Add Time Slot': 'Saat Dilimi Ekle',
      'Add New Slot': 'Yeni Saat Dilimi Ekle',
      'Edit Time Slot': 'Saat Dilimini Düzenle',
      'Update Slot': 'Saat Dilimini Güncelle',
      'Save Slot': 'Saat Dilimini Kaydet',
      'Cancel Edit': 'Düzenlemeyi İptal Et',
      'Time (e.g. 08:30)': 'Saat (Örn: 08:30)',
      'Active Status': 'Aktiflik Durumu',
      'Dynamic Scheduling': 'Dinamik Planlama',
      'Changes made here will immediately appear in the reservation form and filtering options.': 'Burada yapılan değişiklikler anında rezervasyon formunda ve filtreleme seçeneklerinde görünür.',
      'No flight times defined.': 'Tanımlanmış uçuş saati bulunamadı.',

      // Exchange Rates
      'Refresh Rates': 'Kurları Yenile',
      'Refreshing...': 'Yenileniyor...',
      'Currency Converter': 'Döviz Çevirici',
      'Amount to Convert': 'Çevrilecek Tutar',
      'From': 'Kaynak Birim',
      'To': 'Hedef Birim',
      'Converted Amount': 'Çevrilen Tutar',
      'Detailed Conversion Table (Base: 1 USD)': 'Ayrıntılı Çeviri Tablosu (Baz: 1 USD)',
      'Currency Code': 'Para Birimi Kodu',
      'Currency Name': 'Para Birimi Adı',
      'Rate to 1 USD': '1 USD Karşılığı',
      'Rate to 1 TRY': '1 TRY Karşılığı',
      'Last updated:': 'Son güncelleme:',

      // Payments
      'Payments Management': 'Ödeme Yönetimi',
      'Payment Hub': 'Ödeme Merkezi',
      'Collect Payments': 'Ödeme Al',
      'Payment Records': 'Ödeme Kayıtları',
      'Daily Revenue Ledger': 'Günlük Gelir Defteri',
      'Select Date:': 'Tarih Seçin:',
      'Transactions': 'İşlemler / Hareketler',
      'TRY Collected': 'Tahsil Edilen TRY',
      'USD Collected': 'Tahsil Edilen USD',
      'EUR Collected': 'Tahsil Edilen EUR',
      'GBP Collected': 'Tahsil Edilen GBP',
      'Payment Method': 'Ödeme Yöntemi',
      'All Methods': 'Tüm Yöntemler',
      'All Currencies': 'Tüm Para Birimleri',
      'Start Date': 'Başlangıç Tarihi',
      'End Date': 'Bitiş Tarihi',
      'Search by Reservation ID, Title, or Passenger Name...': 'Rezervasyon No, Başlık veya Yolcu Adı ile Ara...',
      'Amount Paid': 'Ödenen Tutar',
      'Method': 'Yöntem',
      'No transaction records found matching your filters.': 'Filtrelerinize uygun işlem kaydı bulunamadı.',
      'No flights scheduled for this slot.': 'Bu saat dilimi için planlanmış uçuş yok.',
      'Paid in Full': 'Tamamı Ödendi',
      'Paid': 'Ödendi',
      'Non Paid': 'Ödenmedi',
      'Pending Balance': 'Kalan Bakiye',
      'Rest to Pay': 'Kalan Tutar',
      'Cash': 'Nakit',
      'Credit Card': 'Kredi Kartı',
      'Card': 'Kart',
      'Bank Transfer': 'Banka Havalesi',
      'Transfer': 'Havale',
      'Transfer/IBAN': 'Havale / IBAN',
      'Refund': 'İade',
      'Receipt': 'Makbuz / Fiş',
      'Make Payment': 'Ödeme Yap',
      'Issue Refund': 'İade Yap',
      'Deposit': 'Depozito',
      'Pay': 'Öde',
      'Print Thermal Bill (80mm)': 'Termal Fiş Yazdır (80mm)',
      'Payment': 'Ödeme',
      'Confirm Payment': 'Ödemeyi Onayla',
      'Confirm Refund': 'İadeyi Onayla',
      'Pay All': 'Tümünü Öde',
      'Refund All': 'Tümünü İade Et',
      'Refund Amount': 'İade Tutarı',
      'Pay in Currency': 'Ödeme Para Birimi',
      'Rest': 'Kalan',
      'Equivalent in': 'Karşılığı',
      'Exchange Rate': 'Döviz Kuru',

      // Reservations & Reservation Form
      'Reservations Dashboard': 'Rezervasyon Kontrol Paneli',
      'Schedule View': 'Uçuş Takvimi',
      'Schedule Matrix': 'Uçuş Takvimi (Kanban)',
      'List View': 'Liste Görünümü',
      'Print PDF': 'PDF Yazdır',
      'Print PDF Manifest': 'Uçuş Listesini PDF Yazdır',
      'Print Voucher': 'Kuponu Yazdır',
      'Slots': 'Kayıt',
      'No reservations for this slot.': 'Bu saat dilimi için rezervasyon yok.',
      'PAX': 'Yolcu',
      'Reservation Title': 'Rezervasyon Başlığı',
      'Booking Source': 'Rezervasyon Kaynağı',
      'Flight Date': 'Uçuş Tarihi',
      'Booking Status': 'Rezervasyon Durumu',
      'Booking Channel': 'Rezervasyon Kanalı',
      'Direct Booking (Us)': 'Doğrudan Rezervasyon (Bizim)',
      'Direct Booking': 'Doğrudan Rezervasyon',
      'Agency Booking': 'Acente Rezervasyonu',
      'Agency': 'Acente',
      'Select Agency': 'Acente Seçin',
      'Pickup Hotel': 'Alınış Oteli',
      'Room Number': 'Oda Numarası',
      'Passenger Weight': 'Yolcu Kilosu',
      'Weight': 'Kilo (kg)',
      'Assigned Pilot': 'Atanan Pilot',
      'Takeoff Time': 'Kalkış Saati',
      'Passengers Details': 'Yolcu Detayları',
      'Add Passenger': 'Yolcu Ekle',
      'Total Due': 'Toplam Tutar',
      'Deposit Paid': 'Ödenen Depozito',
      'Payment Currency': 'Ödeme Para Birimi',
      'Preferred Currency': 'Tercih Edilen Para Birimi',
      'Total Amount': 'Toplam Tutar',
      'Billet Number': 'Bilet Numarası',
      'Billet / Ticket Number': 'Bilet Numarası',
      'Passenger Information': 'Yolcu Bilgileri',
      'Passenger Details': 'Yolcu Detayları',
      'Search Existing Customer': 'Kayıtlı Müşteri Ara',
      'Start typing name...': 'İsim yazmaya başlayın...',
      'Nationality': 'Uyruk',
      'Select Country': 'Ülke Seçin',
      'Filter by Group': 'Gruba Göre Filtrele',
      'Select Pilot': 'Pilot Seçin',
      'Flight Package': 'Uçuş Paketi',
      'Choose Package': 'Paket Seçin',
      'Transport': 'Transfer / Servis',
      'Select Service': 'Servis Seçin',
      'Select Extras': 'Ek Hizmetleri Seçin',
      'Passenger Weight Limit Verified': 'Yolcu Kilo Sınırı Doğrulandı',
      'Add Another Passenger to this Reservation': 'Bu Rezervasyona Başka Bir Yolcu Ekle',
      'Pickup & Logistics': 'Alınış ve Lojistik',
      'Pickup Service': 'Alınış Hizmeti',
      'Pickup Location / Hotel Name': 'Alınış Yeri / Otel Adı',
      'Enter hotel or location name': 'Otel veya konum adı girin',
      'Additional Information': 'Ek Bilgiler',
      'Special Requests or Notes': 'Özel Talepler ve Notlar',
      'Any dietary requirements, health issues, or special occasions?': 'Özel gereksinimler, sağlık durumları veya özel günler?',
      'Reservation Photos / Documents': 'Rezervasyon Fotoğrafları / Belgeleri',
      'Upload Photos (e.g. payment receipt, passport copy, ticket files)': 'Fotoğraf Yükle (Dekont, Pasaport, Bilet)',
      'Drag & drop files here, or click to browse': 'Dosyaları buraya sürükleyin veya seçin',
      'Choose Photos': 'Fotoğraf Seç',
      'Complete Booking': 'Rezervasyonu Tamamla',
      'Update Reservation': 'Rezervasyonu Güncelle',
      'Please provide the flight and passenger details below.': 'Lütfen uçuş ve yolcu detaylarını aşağıda belirtin.',
      'Book a New Flight': 'Yeni Uçuş Rezervasyonu Yap',
      'Update Flight Details': 'Uçuş Detaylarını Güncelle',
      'Loading reservations...': 'Rezervasyonlar yükleniyor...',
      'Saving reservation...': 'Rezervasyon kaydediliyor...',
      'Financial Summary': 'Finansal Özet',
      'Total Price': 'Toplam Fiyat',
      'Total Paid': 'Toplam Ödenen',
      'Remaining Due': 'Kalan Borç',
      'Booking Channels': 'Rezervasyon Kanalları',
      'Booking Overview': 'Rezervasyon Özeti',
      'Total PAX (Passengers)': 'Toplam Yolcu Sayısı (PAX)',
      'No channel data available': 'Kanal verisi bulunamadı',
      'No reservations found matching your criteria.': 'Kriterlerinize uygun rezervasyon bulunamadı.',
      'Date Range': 'Tarih Aralığı',
      'Selected Day': 'Seçilen Gün',
      'One Week': 'Bir Hafta',
      'One Month': 'Bir Ay',
      'One Year': 'Bir Yıl',
      'All Time': 'Tüm Zamanlar',
      'All Statuses': 'Tüm Durumlar',
      'All Times': 'Tüm Saatler',
      'Title / Type': 'Başlık / Tür',
      'Amount / Paid': 'Tutar / Ödenen',

      // User Management & Profile
      'User Management': 'Kullanıcı Yönetimi',
      'System Users': 'Sistem Kullanıcıları',
      'Add New User': 'Yeni Kullanıcı Ekle',
      'User': 'Kullanıcı',
      'Roles': 'Roller',
      'Reset Password': 'Şifreyi Sıfırla',
      'User Profile': 'Kullanıcı Profili',
      'Profile': 'Profil',
      'Profile Details': 'Profil Detayları',
      'Account Type': 'Hesap Türü',
      'Member Since': 'Üyelik Tarihi',
      'Overview': 'Genel Bakış'
    }
  };

  constructor() {}

  private getInitialLanguage(): SupportedLanguage {
    const saved = localStorage.getItem('lang')?.toLowerCase();
    if (saved === 'tr') return 'tr';
    return 'en'; // Default to English
  }

  public get currentLanguage(): SupportedLanguage {
    return this.currentLangSubject.value;
  }

  public setLanguage(lang: SupportedLanguage): void {
    if (lang !== 'en' && lang !== 'tr') {
      lang = 'en';
    }
    localStorage.setItem('lang', lang);
    this.currentLangSubject.next(lang);
  }

  public translate(key: string): string {
    if (!key) return '';
    const currentLang = this.currentLangSubject.value;
    const dict = this.translations[currentLang];
    if (dict && dict[key] !== undefined) {
      return dict[key];
    }
    // Fallback to English if available
    const enDict = this.translations['en'];
    if (enDict && enDict[key] !== undefined) {
      return enDict[key];
    }
    return key;
  }
}
